### ISSUE TITLE
Using selectors with props

### ISSUE THREAD

**Issue by BorisZubchenko** [co-IT/ngrx-ducks#33]
The `bindSelectors` function accepts only `MemoizedSelector`. It creates problems when selector list has `MemoizedSelectorWithProps` item.

I see that the decision was made since it's unclear how to update the existing API.  
I'd like to discuss the ability to make `bindSelectors` accept `MemoizedSelectorWithProps` as well even if we cannot use it as it should be (maybe we can select them with a store).

I really love the way I encapsulate my selectors and make it accessible from facades only. I was trying `usePick` approach but it makes my selectors global-wide.

**Comment by GregOnNet** [comment]
This is also a good catch.
Technically I am not able to do this yet.

This is because I can not differentiate plain selectors and selectors with props at runtime.
Both are similar.

I can differentiate on the type-level but not at runtime.
I planend to ask the NgRx-Team to support this.

I need to open an issue for that.

**Comment by GregOnNet** [comment]
@BorisZubchenko NgRx Ducks 12.1 supports Selector Factories.
Example: https://stackblitz.com/edit/ngrx-ducks-12

The only thing you need to do is writing a selector wrapped by a factory:

```ts
export const currentCountWithOffset = (offset: number) =>
  createSelector(
    visitCounter,
    counter => counter.simple.count + offset
  );
```

NgRx Ducks will consume this factory and transform it to a new function, instrumenting the Store to return an Observable.
